name: daily-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
dependabot/github_actions/dailydotdev/action-devcard-3.1.0
        uses: dailydotdev/action-devcard@3.1.0
 main
        with:
          user_id: ${{ secrets.USER_ID }}
          commit_message: "chore: update ${filename}"
